import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@components/header/Header";
import Footer from "@components/footer/Footer";
import CustomCursor from "@components/cursor/CustomCursor";
import PageTransition from "@components/transitions/PageTransition";
import "./globals.scss";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Digital Experience Architect",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<CustomCursor />
				<Header />
				<PageTransition>{children}</PageTransition>
				<Footer />
			</body>
		</html>
	);
}
